### PR TITLE
Update react-router.js

### PR DESCRIPTION
**Pull request by MichaelDeBoey**

### CODE REVIEW

**Review by kentcdodds — APPROVED** [review]
Solid

**Comment by MichaelDeBoey** [comment]
This was the last one 😅

**Comment by kentcdodds** [comment]
Thanks! It's a lot better now :)

**Comment by MichaelDeBoey** [comment]
Updated the docs too 🙂

**Comment by kentcdodds** [comment]
youre awesome

**Comment by MichaelDeBoey** [comment]
Just doing my share 😉

**Comment by MichaelDeBoey** [comment]
https://github.com/testing-library/testing-library-docs/pull/622

**Pull request merged**
